// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: protos/simulation.proto

package simulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	DiffusionRate float64                `protobuf:"fixed64,3,opt,name=diffusion_rate,json=diffusionRate,proto3" json:"diffusion_rate,omitempty"`
	TimeSteps     int32                  `protobuf:"varint,4,opt,name=time_steps,json=timeSteps,proto3" json:"time_steps,omitempty"`
	DeltaT        float64                `protobuf:"fixed64,5,opt,name=delta_t,json=deltaT,proto3" json:"delta_t,omitempty"`
	DeltaX        float64                `protobuf:"fixed64,6,opt,name=delta_x,json=deltaX,proto3" json:"delta_x,omitempty"` // Initial hot spots could be added here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatParams) Reset() {
	*x = HeatParams{}
	mi := &file_protos_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatParams) ProtoMessage() {}

func (x *HeatParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatParams.ProtoReflect.Descriptor instead.
func (*HeatParams) Descriptor() ([]byte, []int) {
	return file_protos_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *HeatParams) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *HeatParams) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HeatParams) GetDiffusionRate() float64 {
	if x != nil {
		return x.DiffusionRate
	}
	return 0
}

func (x *HeatParams) GetTimeSteps() int32 {
	if x != nil {
		return x.TimeSteps
	}
	return 0
}

func (x *HeatParams) GetDeltaT() float64 {
	if x != nil {
		return x.DeltaT
	}
	return 0
}

func (x *HeatParams) GetDeltaX() float64 {
	if x != nil {
		return x.DeltaX
	}
	return 0
}

type HeatResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data          []float64              `protobuf:"fixed64,3,rep,packed,name=data,proto3" json:"data,omitempty"` // Row-major flattened grid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatResult) Reset() {
	*x = HeatResult{}
	mi := &file_protos_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatResult) ProtoMessage() {}

func (x *HeatResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatResult.ProtoReflect.Descriptor instead.
func (*HeatResult) Descriptor() ([]byte, []int) {
	return file_protos_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *HeatResult) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *HeatResult) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HeatResult) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type NBodyParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumBodies     int32                  `protobuf:"varint,1,opt,name=num_bodies,json=numBodies,proto3" json:"num_bodies,omitempty"`
	TimeSteps     int32                  `protobuf:"varint,2,opt,name=time_steps,json=timeSteps,proto3" json:"time_steps,omitempty"`
	DeltaT        float64                `protobuf:"fixed64,3,opt,name=delta_t,json=deltaT,proto3" json:"delta_t,omitempty"`
	GConstant     float64                `protobuf:"fixed64,4,opt,name=g_constant,json=gConstant,proto3" json:"g_constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NBodyParams) Reset() {
	*x = NBodyParams{}
	mi := &file_protos_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NBodyParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NBodyParams) ProtoMessage() {}

func (x *NBodyParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NBodyParams.ProtoReflect.Descriptor instead.
func (*NBodyParams) Descriptor() ([]byte, []int) {
	return file_protos_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *NBodyParams) GetNumBodies() int32 {
	if x != nil {
		return x.NumBodies
	}
	return 0
}

func (x *NBodyParams) GetTimeSteps() int32 {
	if x != nil {
		return x.TimeSteps
	}
	return 0
}

func (x *NBodyParams) GetDeltaT() float64 {
	if x != nil {
		return x.DeltaT
	}
	return 0
}

func (x *NBodyParams) GetGConstant() float64 {
	if x != nil {
		return x.GConstant
	}
	return 0
}

type BodyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Mass          float64                `protobuf:"fixed64,3,opt,name=mass,proto3" json:"mass,omitempty"`
	Vx            float64                `protobuf:"fixed64,4,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            float64                `protobuf:"fixed64,5,opt,name=vy,proto3" json:"vy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyState) Reset() {
	*x = BodyState{}
	mi := &file_protos_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyState) ProtoMessage() {}

func (x *BodyState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyState.ProtoReflect.Descriptor instead.
func (*BodyState) Descriptor() ([]byte, []int) {
	return file_protos_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *BodyState) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BodyState) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BodyState) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *BodyState) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *BodyState) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

type NBodyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         int32                  `protobuf:"varint,1,opt,name=steps,proto3" json:"steps,omitempty"`
	NumBodies     int32                  `protobuf:"varint,2,opt,name=num_bodies,json=numBodies,proto3" json:"num_bodies,omitempty"`
	FinalState    []*BodyState           `protobuf:"bytes,3,rep,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`                // Just the final state for now, or we could stream all steps
	AllPositions  []float64              `protobuf:"fixed64,4,rep,packed,name=all_positions,json=allPositions,proto3" json:"all_positions,omitempty"` // Flat list of (x, y) for all bodies for all steps [step1_b1_x, step1_b1_y, step1_b2_x...]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NBodyResult) Reset() {
	*x = NBodyResult{}
	mi := &file_protos_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NBodyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NBodyResult) ProtoMessage() {}

func (x *NBodyResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NBodyResult.ProtoReflect.Descriptor instead.
func (*NBodyResult) Descriptor() ([]byte, []int) {
	return file_protos_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *NBodyResult) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *NBodyResult) GetNumBodies() int32 {
	if x != nil {
		return x.NumBodies
	}
	return 0
}

func (x *NBodyResult) GetFinalState() []*BodyState {
	if x != nil {
		return x.FinalState
	}
	return nil
}

func (x *NBodyResult) GetAllPositions() []float64 {
	if x != nil {
		return x.AllPositions
	}
	return nil
}

var File_protos_simulation_proto protoreflect.FileDescriptor

const file_protos_simulation_proto_rawDesc = "" +
	"\n" +
	"\x17protos/simulation.proto\x12\n" +
	"simulation\"\xb2\x01\n" +
	"\n" +
	"HeatParams\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12%\n" +
	"\x0ediffusion_rate\x18\x03 \x01(\x01R\rdiffusionRate\x12\x1d\n" +
	"\n" +
	"time_steps\x18\x04 \x01(\x05R\ttimeSteps\x12\x17\n" +
	"\adelta_t\x18\x05 \x01(\x01R\x06deltaT\x12\x17\n" +
	"\adelta_x\x18\x06 \x01(\x01R\x06deltaX\"N\n" +
	"\n" +
	"HeatResult\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x12\n" +
	"\x04data\x18\x03 \x03(\x01R\x04data\"\x83\x01\n" +
	"\vNBodyParams\x12\x1d\n" +
	"\n" +
	"num_bodies\x18\x01 \x01(\x05R\tnumBodies\x12\x1d\n" +
	"\n" +
	"time_steps\x18\x02 \x01(\x05R\ttimeSteps\x12\x17\n" +
	"\adelta_t\x18\x03 \x01(\x01R\x06deltaT\x12\x1d\n" +
	"\n" +
	"g_constant\x18\x04 \x01(\x01R\tgConstant\"[\n" +
	"\tBodyState\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x12\n" +
	"\x04mass\x18\x03 \x01(\x01R\x04mass\x12\x0e\n" +
	"\x02vx\x18\x04 \x01(\x01R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x05 \x01(\x01R\x02vy\"\x9f\x01\n" +
	"\vNBodyResult\x12\x14\n" +
	"\x05steps\x18\x01 \x01(\x05R\x05steps\x12\x1d\n" +
	"\n" +
	"num_bodies\x18\x02 \x01(\x05R\tnumBodies\x126\n" +
	"\vfinal_state\x18\x03 \x03(\v2\x15.simulation.BodyStateR\n" +
	"finalState\x12#\n" +
	"\rall_positions\x18\x04 \x03(\x01R\fallPositions2\x9b\x01\n" +
	"\x11SimulationService\x12C\n" +
	"\x11SolveHeatEquation\x12\x16.simulation.HeatParams\x1a\x16.simulation.HeatResult\x12A\n" +
	"\rSimulateNBody\x12\x17.simulation.NBodyParams\x1a\x17.simulation.NBodyResultB4Z2github.com/simulation-app/backend-go/pb/simulationb\x06proto3"

var (
	file_protos_simulation_proto_rawDescOnce sync.Once
	file_protos_simulation_proto_rawDescData []byte
)

func file_protos_simulation_proto_rawDescGZIP() []byte {
	file_protos_simulation_proto_rawDescOnce.Do(func() {
		file_protos_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_simulation_proto_rawDesc), len(file_protos_simulation_proto_rawDesc)))
	})
	return file_protos_simulation_proto_rawDescData
}

var file_protos_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_simulation_proto_goTypes = []any{
	(*HeatParams)(nil),  // 0: simulation.HeatParams
	(*HeatResult)(nil),  // 1: simulation.HeatResult
	(*NBodyParams)(nil), // 2: simulation.NBodyParams
	(*BodyState)(nil),   // 3: simulation.BodyState
	(*NBodyResult)(nil), // 4: simulation.NBodyResult
}
var file_protos_simulation_proto_depIdxs = []int32{
	3, // 0: simulation.NBodyResult.final_state:type_name -> simulation.BodyState
	0, // 1: simulation.SimulationService.SolveHeatEquation:input_type -> simulation.HeatParams
	2, // 2: simulation.SimulationService.SimulateNBody:input_type -> simulation.NBodyParams
	1, // 3: simulation.SimulationService.SolveHeatEquation:output_type -> simulation.HeatResult
	4, // 4: simulation.SimulationService.SimulateNBody:output_type -> simulation.NBodyResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_simulation_proto_init() }
func file_protos_simulation_proto_init() {
	if File_protos_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_simulation_proto_rawDesc), len(file_protos_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_simulation_proto_goTypes,
		DependencyIndexes: file_protos_simulation_proto_depIdxs,
		MessageInfos:      file_protos_simulation_proto_msgTypes,
	}.Build()
	File_protos_simulation_proto = out.File
	file_protos_simulation_proto_goTypes = nil
	file_protos_simulation_proto_depIdxs = nil
}
