// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: protos/ai.proto

package ai

import (
	simulation "github.com/simulation-app/backend-go/pb/simulation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatGoal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetProperty string                 `protobuf:"bytes,1,opt,name=target_property,json=targetProperty,proto3" json:"target_property,omitempty"` // e.g. "fast_diffusion", "stable"
	DesiredValue   float64                `protobuf:"fixed64,2,opt,name=desired_value,json=desiredValue,proto3" json:"desired_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeatGoal) Reset() {
	*x = HeatGoal{}
	mi := &file_protos_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatGoal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatGoal) ProtoMessage() {}

func (x *HeatGoal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatGoal.ProtoReflect.Descriptor instead.
func (*HeatGoal) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{0}
}

func (x *HeatGoal) GetTargetProperty() string {
	if x != nil {
		return x.TargetProperty
	}
	return ""
}

func (x *HeatGoal) GetDesiredValue() float64 {
	if x != nil {
		return x.DesiredValue
	}
	return 0
}

type NBodyGoal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetBehavior string                 `protobuf:"bytes,1,opt,name=target_behavior,json=targetBehavior,proto3" json:"target_behavior,omitempty"` // e.g. "minimize_collisions", "orbital_stability"
	BodyCount      int32                  `protobuf:"varint,2,opt,name=body_count,json=bodyCount,proto3" json:"body_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NBodyGoal) Reset() {
	*x = NBodyGoal{}
	mi := &file_protos_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NBodyGoal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NBodyGoal) ProtoMessage() {}

func (x *NBodyGoal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NBodyGoal.ProtoReflect.Descriptor instead.
func (*NBodyGoal) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{1}
}

func (x *NBodyGoal) GetTargetBehavior() string {
	if x != nil {
		return x.TargetBehavior
	}
	return ""
}

func (x *NBodyGoal) GetBodyCount() int32 {
	if x != nil {
		return x.BodyCount
	}
	return 0
}

var File_protos_ai_proto protoreflect.FileDescriptor

const file_protos_ai_proto_rawDesc = "" +
	"\n" +
	"\x0fprotos/ai.proto\x12\x02ai\x1a\x17protos/simulation.proto\"X\n" +
	"\bHeatGoal\x12'\n" +
	"\x0ftarget_property\x18\x01 \x01(\tR\x0etargetProperty\x12#\n" +
	"\rdesired_value\x18\x02 \x01(\x01R\fdesiredValue\"S\n" +
	"\tNBodyGoal\x12'\n" +
	"\x0ftarget_behavior\x18\x01 \x01(\tR\x0etargetBehavior\x12\x1d\n" +
	"\n" +
	"body_count\x18\x02 \x01(\x05R\tbodyCount2\x8d\x01\n" +
	"\x10OptimizerService\x12:\n" +
	"\x12OptimizeHeatParams\x12\f.ai.HeatGoal\x1a\x16.simulation.HeatParams\x12=\n" +
	"\x13OptimizeNBodyParams\x12\r.ai.NBodyGoal\x1a\x17.simulation.NBodyParamsB,Z*github.com/simulation-app/backend-go/pb/aib\x06proto3"

var (
	file_protos_ai_proto_rawDescOnce sync.Once
	file_protos_ai_proto_rawDescData []byte
)

func file_protos_ai_proto_rawDescGZIP() []byte {
	file_protos_ai_proto_rawDescOnce.Do(func() {
		file_protos_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ai_proto_rawDesc), len(file_protos_ai_proto_rawDesc)))
	})
	return file_protos_ai_proto_rawDescData
}

var file_protos_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_ai_proto_goTypes = []any{
	(*HeatGoal)(nil),               // 0: ai.HeatGoal
	(*NBodyGoal)(nil),              // 1: ai.NBodyGoal
	(*simulation.HeatParams)(nil),  // 2: simulation.HeatParams
	(*simulation.NBodyParams)(nil), // 3: simulation.NBodyParams
}
var file_protos_ai_proto_depIdxs = []int32{
	0, // 0: ai.OptimizerService.OptimizeHeatParams:input_type -> ai.HeatGoal
	1, // 1: ai.OptimizerService.OptimizeNBodyParams:input_type -> ai.NBodyGoal
	2, // 2: ai.OptimizerService.OptimizeHeatParams:output_type -> simulation.HeatParams
	3, // 3: ai.OptimizerService.OptimizeNBodyParams:output_type -> simulation.NBodyParams
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ai_proto_init() }
func file_protos_ai_proto_init() {
	if File_protos_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ai_proto_rawDesc), len(file_protos_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ai_proto_goTypes,
		DependencyIndexes: file_protos_ai_proto_depIdxs,
		MessageInfos:      file_protos_ai_proto_msgTypes,
	}.Build()
	File_protos_ai_proto = out.File
	file_protos_ai_proto_goTypes = nil
	file_protos_ai_proto_depIdxs = nil
}
