// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: protos/ai.proto

package ai

import (
	context "context"
	simulation "github.com/simulation-app/backend-go/pb/simulation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizerService_OptimizeHeatParams_FullMethodName  = "/ai.OptimizerService/OptimizeHeatParams"
	OptimizerService_OptimizeNBodyParams_FullMethodName = "/ai.OptimizerService/OptimizeNBodyParams"
)

// OptimizerServiceClient is the client API for OptimizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizerServiceClient interface {
	OptimizeHeatParams(ctx context.Context, in *HeatGoal, opts ...grpc.CallOption) (*simulation.HeatParams, error)
	OptimizeNBodyParams(ctx context.Context, in *NBodyGoal, opts ...grpc.CallOption) (*simulation.NBodyParams, error)
}

type optimizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizerServiceClient(cc grpc.ClientConnInterface) OptimizerServiceClient {
	return &optimizerServiceClient{cc}
}

func (c *optimizerServiceClient) OptimizeHeatParams(ctx context.Context, in *HeatGoal, opts ...grpc.CallOption) (*simulation.HeatParams, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(simulation.HeatParams)
	err := c.cc.Invoke(ctx, OptimizerService_OptimizeHeatParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) OptimizeNBodyParams(ctx context.Context, in *NBodyGoal, opts ...grpc.CallOption) (*simulation.NBodyParams, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(simulation.NBodyParams)
	err := c.cc.Invoke(ctx, OptimizerService_OptimizeNBodyParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizerServiceServer is the server API for OptimizerService service.
// All implementations must embed UnimplementedOptimizerServiceServer
// for forward compatibility.
type OptimizerServiceServer interface {
	OptimizeHeatParams(context.Context, *HeatGoal) (*simulation.HeatParams, error)
	OptimizeNBodyParams(context.Context, *NBodyGoal) (*simulation.NBodyParams, error)
	mustEmbedUnimplementedOptimizerServiceServer()
}

// UnimplementedOptimizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizerServiceServer struct{}

func (UnimplementedOptimizerServiceServer) OptimizeHeatParams(context.Context, *HeatGoal) (*simulation.HeatParams, error) {
	return nil, status.Error(codes.Unimplemented, "method OptimizeHeatParams not implemented")
}
func (UnimplementedOptimizerServiceServer) OptimizeNBodyParams(context.Context, *NBodyGoal) (*simulation.NBodyParams, error) {
	return nil, status.Error(codes.Unimplemented, "method OptimizeNBodyParams not implemented")
}
func (UnimplementedOptimizerServiceServer) mustEmbedUnimplementedOptimizerServiceServer() {}
func (UnimplementedOptimizerServiceServer) testEmbeddedByValue()                          {}

// UnsafeOptimizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizerServiceServer will
// result in compilation errors.
type UnsafeOptimizerServiceServer interface {
	mustEmbedUnimplementedOptimizerServiceServer()
}

func RegisterOptimizerServiceServer(s grpc.ServiceRegistrar, srv OptimizerServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizerService_ServiceDesc, srv)
}

func _OptimizerService_OptimizeHeatParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeatGoal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).OptimizeHeatParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_OptimizeHeatParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).OptimizeHeatParams(ctx, req.(*HeatGoal))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_OptimizeNBodyParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NBodyGoal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).OptimizeNBodyParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_OptimizeNBodyParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).OptimizeNBodyParams(ctx, req.(*NBodyGoal))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizerService_ServiceDesc is the grpc.ServiceDesc for OptimizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.OptimizerService",
	HandlerType: (*OptimizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OptimizeHeatParams",
			Handler:    _OptimizerService_OptimizeHeatParams_Handler,
		},
		{
			MethodName: "OptimizeNBodyParams",
			Handler:    _OptimizerService_OptimizeNBodyParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/ai.proto",
}
